### ISSUE TITLE
Could support pymongo

### ISSUE THREAD

**Issue by lietu** [lietu/shylock#1]
No real reason why this library must only have `async` support, could rename `Lock` to `AsyncLock` or similar, and leave `Lock` to be synchronous, or put the async code in an `asyncio` namespace.

Would likely be easiest to then just support plain `pymongo` instead of `motor` as MongoDB is mostly the same anyway.

**Comment by joakimnordling** [comment]
@lietu: Seems like you added support for pymongo already, but left this issue open.
